apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  inbound:
    - name: DonorLoop Service
      port: 8080
      type: REST
      networkVisibility: Public
      context: /donor-loop
      endpoints:
        - path: /blood-availability
          method: POST
          operationId: addBloodAvailability
        - path: /blood-availability/{bloodBankId}
          method: GET
          operationId: getBloodAvailabilityByBloodBankId
        - path: /blood-availability/{bloodAvailabilityId}
          method: PUT
          operationId: updateBloodAvailability

